### ISSUE TITLE
Create event not working

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#400] opened 2021-01-25 00:36 UTC
## Notice
I'm tagging the frontend member that implemented this page (@UkcaGreen ) and members from the backend team (@isiktashamza , @EnesToptas ). First, the cause of this bug should be found, and the responsible team should take action.

## Description
The event creation page seems to work well, until you hit `Confirm`. This displays an error message that reads `Event posting failed`. 

## Error Message
```
xhr.js:177 POST http://ec2-18-232-99-241.compute-1.amazonaws.com:3000/event/add 500 (Internal Server Error)
```
```
http://ec2-18-232-99-241.compute-1.amazonaws.com:3000/event/add
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

## How To Reproduce
1. Login as any user
2. Click 'Create new event' on profile sider (the sidebar that shows up on the home page)
3. Fill details about an event
4. Click confirm

**Comment by EnesToptas** [comment] 2021-01-25 11:24
This seems to be due to a misunderstanding, and now works as intended. Closing.

**Closed by EnesToptas** 2021-01-25 11:24 UTC
Labels: backend, bug, frontend, high priority, urgent
